# Generated by Django 5.2.5 on 2025-08-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients_logos',
            new_name='Clients_logo',
        ),
    ]
