# Generated by Django 5.2.5 on 2025-08-19 21:42

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0002_rename_clients_logos_clients_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=100)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('rating', models.IntegerField(help_text='Rating (1 to 5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='clients_logo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='clients_logo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clients_logo',
            name='Brand_Logo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, verbose_name='image'),
        ),
    ]
