# Generated by Django 5.2.5 on 2025-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0003_testimonial_alter_clients_logo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients_logo',
            name='Brand_Url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
