# Generated by Django 5.2.5 on 2025-08-20 15:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0004_clients_logo_brand_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=200)),
                ('full_description', models.TextField()),
                ('category', models.CharField(choices=[('Web Application', 'Web Applications'), ('Mobile Application', 'Mobile Applications'), ('API & Backend Service', 'APIs & Backend Services'), ('OS & Low-Level Programming', 'OS & Low-Level Programming')], max_length=50)),
                ('launch_date', models.DateField()),
                ('project_url', models.URLField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lusoapp.project')),
            ],
        ),
    ]
