# Generated by Django 5.2.5 on 2025-08-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0005_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='lusoapp.project'),
        ),
    ]
