# Generated by Django 5.2.5 on 2025-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0006_testimonial_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Branding', 'Branding'), ('Strategy Development', 'Strategy Development')], max_length=50),
        ),
    ]
