# Generated by Django 5.2.5 on 2025-08-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0009_blogpost_likes_blogpost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(max_length=150),
        ),
    ]
