# Generated by Django 5.2.5 on 2025-08-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0010_alter_testimonial_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='full_description',
        ),
    ]
