# Generated by Django 5.2.5 on 2025-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0011_remove_project_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Creative & Visual Design', 'Creative & Visual Design'), ('Web Development', 'Web Development'), ('Branding', 'Branding')], max_length=50),
        ),
    ]
