# Generated by Django 5.2.5 on 2025-08-25 13:37

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0013_alter_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='quote2',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
