# Generated by Django 5.2.5 on 2025-08-25 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusoapp', '0014_blogpost_content2_blogpost_image2_blogpost_quote2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='short_description',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sub_heading2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='sub_heading',
            field=models.TextField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
